export PATH="/usr/local/sbin:$PATH"
export EDITOR="/usr/local/bin/nvim"
#------------------------------------------------------------------------------
# Colors
#------------------------------------------------------------------------------
autoload -U colors && colors
export CLICOLOR="yes"

#------------------------------------------------------------------------------
# Completion
#------------------------------------------------------------------------------
autoload -U compinit && compinit 
zmodload -i zsh/complist
setopt auto_menu
setopt complete_in_word

zstyle ':completion:*' list-colors ''

autoload -U promptinit && promptinit

#------------------------------------------------------------------------------
# History
#------------------------------------------------------------------------------
if [ -z $HISTFILE ]; then
    HISTFILE=$HOME/.zsh_history
fi
HISTSIZE=10000
SAVEHIST=10000

setopt append_history
setopt inc_append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt share_history

#------------------------------------------------------------------------------
# Prompt
#------------------------------------------------------------------------------
autoload -U promptinit && promptinit
prompt pure

# http://zanshin.net/2013/02/02/zsh-configuration-from-the-ground-up/
# http://sheerun.net/2014/03/21/how-to-boost-your-vim-productivity/
# https://github.com/myfreeweb/dotfiles/blob/master/zsh/zshrc

#------------------------------------------------------------------------------
# Functions
#------------------------------------------------------------------------------
# Use ctrl-z to return to paused Vim instead of 'fg<Enter>'.
# http://sheerun.net/2014/03/21/how-to-boost-your-vim-productivity/
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


